export const HI_AUTH: Record<string, string> = {
  "Sign up / Sign in": "साइन अप / साइन इन",
  "Who are you?": "आप कौन हैं?",
  "One account per person. The role you choose determines the surface you can use — a help-seeker is never shown the provider surface and vice versa.":
    "प्रति व्यक्ति एक खाता। आपके द्वारा चुनी गई भूमिका यह तय करती है कि आप कौन सा इंटरफ़ेस उपयोग कर सकते हैं — सहायता चाहने वाले को व्यवसायी इंटरफ़ेस कभी नहीं दिखाया जाता और इसके विपरीत भी।",
  "I need legal help": "मुझे कानूनी सहायता चाहिए",
  "Sign in to continue your legal need, view your referral or pro bono assignment, and track your matter.":
    "अपनी कानूनी आवश्यकता आगे बढ़ाने, अपना रेफरल या प्रो बोनो कार्य देखने और अपने मामले पर नज़र रखने के लिए साइन इन करें।",
  "I am a legal professional": "मैं एक कानूनी व्यवसायी हूँ",
  "Sign in to create your professional profile, submit credentials for verification and manage your dashboard.":
    "अपनी पेशेवर प्रोफ़ाइल बनाने, सत्यापन हेतु प्रमाण-पत्र जमा करने और अपना डैशबोर्ड प्रबंधित करने के लिए साइन इन करें।",
  "I operate a CSC / VLE": "मैं CSC / VLE संचालित करता हूँ",
  "Sign in to open a delegated assisted session for a citizen, with recorded consent.":
    "रिकॉर्ड की गई सहमति के साथ किसी नागरिक के लिए प्रत्यायोजित सहायता सत्र शुरू करने के लिए साइन इन करें।",
  "Institution (DLSA / Bar Council / DoJ)": "संस्था (DLSA / बार काउंसिल / DoJ)",
  "Sign in to access scoped institutional surfaces — rosters, aggregate statistics and grievance pipeline.":
    "सीमित संस्थागत इंटरफ़ेस — रोस्टर, समग्र आँकड़े और शिकायत पाइपलाइन तक पहुँचने के लिए साइन इन करें।",
  "Signed in as {role} · {phone}.": "{role} के रूप में साइन इन किया गया · {phone}।",
  "Sign out": "साइन आउट",
  "No active session. Choose a role to continue.": "कोई सक्रिय सत्र नहीं। आगे बढ़ने के लिए कोई भूमिका चुनें।",
  "Sign in — {title}": "साइन इन — {title}",
  "One-time password": "वन-टाइम पासवर्ड",
  "One-time password to your phone. No password to remember.":
    "आपके फ़ोन पर वन-टाइम पासवर्ड। याद रखने के लिए कोई पासवर्ड नहीं।",
  "OTP verifies your phone. Your professional identity is then verified separately through the credential rail — a phone number is never a professional credential.":
    "OTP आपके फ़ोन को सत्यापित करता है। इसके बाद आपकी पेशेवर पहचान प्रमाण-पत्र प्रणाली के माध्यम से अलग से सत्यापित की जाती है — एक फ़ोन नंबर कभी भी पेशेवर प्रमाण-पत्र नहीं होता।",
  "Every assisted action is recorded against both you and the citizen, under a recorded consent reference.":
    "हर सहायता कार्रवाई रिकॉर्ड की गई सहमति संदर्भ के अंतर्गत आप और नागरिक दोनों के नाम पर दर्ज की जाती है।",
  "Scoped, read-mostly access. Aggregate statistics only for public surfaces.":
    "सीमित, मुख्यतः केवल-पठन पहुँच। समग्र आँकड़े केवल सार्वजनिक इंटरफ़ेस के लिए।",
  "Signed in as a different role. Please verify as {role} to continue. You can sign out first if this is not your account.":
    "किसी भिन्न भूमिका में साइन इन किया गया है। आगे बढ़ने के लिए कृपया {role} के रूप में सत्यापित करें। यदि यह आपका खाता नहीं है, तो आप पहले साइन आउट कर सकते हैं।",
  "Signed in as {phone} ({role}).": "{phone} ({role}) के रूप में साइन इन किया गया।",
  Continue: "जारी रखें",
  "Phone number": "फ़ोन नंबर",
  "10-digit mobile number": "10 अंकों का मोबाइल नंबर",
  "Enter OTP": "OTP दर्ज करें",
  "Demo mode: any 4-digit code is accepted.": "डेमो मोड: कोई भी 4 अंकों का कोड स्वीकार किया जाता है।",
  "Failed to send OTP": "OTP भेजने में विफल",
  "Invalid OTP": "अमान्य OTP",
  Verify: "सत्यापित करें",
  "Send OTP": "OTP भेजें",
  "← Choose a different role": "← कोई भिन्न भूमिका चुनें",
  citizen: "नागरिक",
  provider: "व्यवसायी",
  operator: "सहायता-मोड संचालक",
  institution: "संस्था",
  "legal professional": "कानूनी व्यवसायी",
  "assisted-mode operator": "सहायता-मोड संचालक",
  "institutional consumer": "संस्थागत उपभोक्ता",
  "ROLE MISMATCH": "भूमिका बेमेल",
  "SIGNED IN": "साइन इन किया गया",
  "SELF-DECLARED": "स्व-घोषित",
  "DOCUMENT-VERIFIED": "दस्तावेज़-सत्यापित",
  "FULLY VERIFIED": "पूर्ण रूप से सत्यापित",
  VERIFIED: "सत्यापित",
  PENDING: "लंबित",
  TRIAGED: "वर्गीकृत",
  CONFIRMED: "पुष्ट",
  PAYMENT_INITIATED: "भुगतान आरंभ",
  AWAITING_PROVIDER_CONFIRMATION: "व्यवसायी की पुष्टि की प्रतीक्षा",
  PLATFORM_RESOLVED: "प्लेटफ़ॉर्म द्वारा समाधान",
  SETTLED: "निपटाया गया",
  FAILED: "विफल",
  MISMATCH: "बेमेल",
  CONFLICT: "विरोध",
  NOT_FOUND: "नहीं मिला",
  REFERRED_TO_BAR_COUNCIL: "बार काउंसिल को भेजा गया",
  REFERRED_TO_DLSA: "DLSA को भेजा गया",
  SELF_DECLARED: "स्व-घोषित",
  DOCUMENT_VERIFIED: "दस्तावेज़-सत्यापित",
  FULLY_VERIFIED: "पूर्ण रूप से सत्यापित",
  OPEN: "खुला",
  ACTIVE: "सक्रिय",
  LINK_REQUIRED: "लिंक आवश्यक",
  MOCK: "डेमो",
  DEMO_ONLY: "केवल डेमो",
  OFFLINE_ACK: "ऑफ़लाइन स्वीकृति",
  QUOTE_READY: "उद्धरण तैयार",
  ERROR: "त्रुटि",
  ROTATED: "बदला हुआ",
  "REVERIFICATION DUE": "पुनः सत्यापन बाकी",
  "FREE LEGAL AID": "निःशुल्क विधिक सहायता",
  STALE: "पुराना",
  CURRENT: "वर्तमान",
  "DEMO ONLY": "केवल डेमो",
  "APPEND-ONLY": "केवल-संवर्धनीय",
  AVAILABLE: "उपलब्ध",
  BOOKED: "बुक किया गया",
  PAID: "भुगतान किया गया",
  UNAVAILABLE: "अनुपलब्ध",
  OFF: "बंद",
  LIVE: "लाइव",
  "ASSISTED SESSION": "सहायता सत्र",
  "SESSION sess_0938": "सत्र sess_0938",

  /* ---------- onboarding: current-location helper ---------- */
  "Use current location": "वर्तमान स्थान का उपयोग करें",
  "Use location again": "स्थान फिर से प्राप्त करें",
  "Detecting your location…": "आपका स्थान पता लगाया जा रहा है…",
  "AREA FILLED": "क्षेत्र भर दिया गया",
  "Please verify the suggested details and complete your street address.":
    "कृपया सुझाए गए विवरण जाँचें और अपना गली/मोहल्ला पूरा करें।",
  "Fills city, district, state and PIN from your device location — used once, never stored. Every field stays editable.":
    "आपके डिवाइस के स्थान से शहर, ज़िला, राज्य और PIN भरता है — एक बार उपयोग होता है, कभी संग्रहीत नहीं। हर फ़ील्ड संपादन योग्य रहता है।",
  "Location services are not available on this device.": "इस डिवाइस पर स्थान सेवा उपलब्ध नहीं है।",
  "Location permission was denied. Please enter your details manually.":
    "स्थान की अनुमति नहीं मिली। कृपया विवरण स्वयं भरें।",
  "Could not read your device location. Please enter your details manually.":
    "डिवाइस का स्थान नहीं पढ़ा जा सका। कृपया विवरण स्वयं भरें।",
  "Could not determine your area from your location. Please enter it manually.":
    "आपके स्थान से क्षेत्र नहीं पता चल सका। कृपया इसे स्वयं भरें।",
};
