export const HI_DIRECTORY: Record<string, string> = {
  /* ---------- directory / Directory.tsx ---------- */
  ERROR: "त्रुटि",
  "Loading the directory…": "निर्देशिका लोड हो रही है…",
  "Mode A — citizen choice": "मोड A — नागरिक की पसंद",
  "Available legal professionals": "उपलब्ध कानूनी पेशेवर",
  "Results are filtered by your legal need, district, language, service mode and fee ceiling — then ordered by fair rotation. No professional is ranked above another. You choose.":
    "परिणाम आपकी कानूनी आवश्यकता, ज़िले, भाषा, सेवा मोड और शुल्क सीमा के आधार पर फ़िल्टर किए जाते हैं — फिर निष्पक्ष रोटेशन के क्रम में रखे जाते हैं। कोई भी पेशेवर दूसरे से ऊपर नहीं रखा जाता। आप चुनते हैं।",
  "Filter summary": "फ़िल्टर सारांश",
  "Category — {category}": "श्रेणी — {category}",
  "District — {district}": "ज़िला — {district}",
  "Language — {language}": "भाषा — {language}",
  "Fee ceiling — {fee}": "शुल्क सीमा — {fee}",
  none: "कोई सीमा नहीं",
  "{count} eligible professional": "{count} पात्र पेशेवर",
  "{count} eligible professionals": "{count} पात्र पेशेवर",
  ROTATED: "रोटेशन",
  seed: "बीज",
  "(replayable)": "(दोहराने योग्य)",
  ADVOCATE: "अधिवक्ता",
  MEDIATOR: "मध्यस्थ",
  IN_PERSON: "व्यक्तिगत रूप से",
  PHONE: "फ़ोन",
  VIDEO: "वीडियो",
  "FULLY VERIFIED": "पूर्णतः सत्यापित",
  "DOCUMENT-VERIFIED": "दस्तावेज़-सत्यापित",
  "SELF-DECLARED": "स्व-घोषित",
  "REVERIFICATION DUE": "पुनः सत्यापन शेष",
  "Fee range": "शुल्क दायरा",
  "Pro bono available": "प्रो बोनो उपलब्ध",
  "Next slot": "अगला स्लॉट",
  "View profile": "प्रोफ़ाइल देखें",
  "No ratings, no rankings, no recommendations. Ordering is a seeded rotation — the same request always replays the same order.":
    "कोई रेटिंग नहीं, कोई रैंकिंग नहीं, कोई सिफ़ारिश नहीं। क्रम एक सीडेड रोटेशन है — एक ही अनुरोध हमेशा एक ही क्रम दोहराता है।",

  /* ---------- category labels (CATEGORY_LABELS) ---------- */
  Property: "संपत्ति",
  Family: "परिवार",
  Employment: "रोज़गार",
  Consumer: "उपभोक्ता",
  Criminal: "आपराधिक",
  "Tenancy / Rent deposit": "किरायेदारी / किराया जमा",
  Other: "अन्य",

  /* ---------- rotation / Rotation.tsx ---------- */
  "Assigning the next advocate on duty…": "ड्यूटी पर अगले अधिवक्ता का आवंटन हो रहा है…",
  "Mode B — duty rotation": "मोड B — ड्यूटी रोटेशन",
  "Assigned through duty rotation": "ड्यूटी रोटेशन के माध्यम से आवंटित",
  "For {category} needs in your district, advocates serve on a duty roster. You are assigned the next advocate in rotation — not chosen by anyone, and not recommended. Rotation state is fair and replayable.":
    "आपके ज़िले में {category} आवश्यकताओं के लिए अधिवक्ता ड्यूटी रोस्टर पर सेवा देते हैं। आपको रोटेशन में अगला अधिवक्ता आवंटित किया जाता है — किसी के द्वारा चुना नहीं गया, और न ही सिफ़ारिश किया गया। रोटेशन की स्थिति निष्पक्ष और दोहराने योग्य है।",
  "Assigned provider": "आवंटित पेशेवर",
  "Allocation {allocationId} · {assignedAt}": "आवंटन {allocationId} · {assignedAt}",
  "Accept assignment": "आवंटन स्वीकार करें",
  "Declined — back in rotation": "अस्वीकृत — रोटेशन में वापस",
  "Decline with reason": "कारण सहित अस्वीकार करें",
  "You declined. The assignment returns to rotation and a conduct signal (duty accounting, not a public rating) is recorded.":
    "आपने अस्वीकार कर दिया। आवंटन रोटेशन में वापस चला जाता है और एक आचरण संकेत (ड्यूटी लेखा, सार्वजनिक रेटिंग नहीं) दर्ज किया जाता है।",
  "Duty rotation means the next eligible provider is assigned fairly — this is how DLSA panels already work. There is no cost for this route.":
    "ड्यूटी रोटेशन का अर्थ है कि अगला पात्र पेशेवर निष्पक्ष रूप से आवंटित किया जाता है — डीएलएसए पैनल इसी तरह काम करते हैं। इस मार्ग की कोई लागत नहीं है।",

  /* ---------- citizen portal / CitizenPortal.tsx ---------- */
  "Loading your portal…": "आपका पोर्टल लोड हो रहा है…",
  "Citizen portal": "नागरिक पोर्टल",
  "My legal matters": "मेरे कानूनी मामले",
  "Your needs, routes and matter metadata. Engagements are metadata only — who, when, category, status, fee, CNR pointer. No case content is stored here.":
    "आपकी आवश्यकताएँ, मार्ग और मामले का मेटाडेटा। सहभागिताएँ केवल मेटाडेटा हैं — कौन, कब, श्रेणी, स्थिति, शुल्क, सीएनआर संदर्भ। यहाँ कोई मामले की सामग्री संग्रहीत नहीं होती।",
  "An empty court corridor with light shafts": "प्रकाश की किरणों वाला एक खाली न्यायालय गलियारा",
  "My needs": "मेरी आवश्यकताएँ",
  "LEGAL AID": "विधिक सहायता",
  "PRO BONO": "प्रो बोनो",
  PAID: "भुगतान किया गया",
  APP: "ऐप",
  ASSISTED: "सहायित",
  IVR: "आईवीआर",
  WHATSAPP: "व्हाट्सऐप",
  "Section 12: {label}": "धारा 12: {label}",
  "No Section 12 declaration": "कोई धारा 12 घोषणा नहीं",
  "Fee ceiling: {amount}": "शुल्क सीमा: {amount}",
  "not stated": "बताई नहीं गई",
  "View referral": "रेफरल देखें",
  "My assigned advocate": "मेरा आवंटित अधिवक्ता",
  Directory: "निर्देशिका",
  Matters: "मामले",
  CLOSED: "बंद",
  ACTIVE: "सक्रिय",
  OPEN: "खुला",
  "s.12 / pro bono — free": "धारा 12 / प्रो बोनो — निःशुल्क",
  "opened {date}": "{date} को खोला गया",
  "No CNR pointer yet": "अभी कोई सीएनआर संदर्भ नहीं",
  "Closed: LEGAL_AID_TIER_MATTER_CLOSED": "बंद: विधिक सहायता स्तर का मामला बंद",
  "Closed: LOK_ADALAT_SETTLEMENT": "बंद: लोक अदालत समाधान",
  Open: "खुला",
  "Matter status is shown through an authorized integration when available — otherwise an official link to the eCourts flow is provided.":
    "जब उपलब्ध हो, मामले की स्थिति एक अधिकृत एकीकरण के माध्यम से दिखाई जाती है — अन्यथा ई-कोर्ट्स प्रक्रिया का एक आधिकारिक लिंक प्रदान किया जाता है।",
  Actions: "क्रियाएँ",
  "Start a new need": "नई आवश्यकता शुरू करें",
  "File a grievance": "शिकायत दर्ज करें",

  /* ---------- Section 12 labels (SECTION12_LABELS) ---------- */
  "Member of a Scheduled Caste": "अनुसूचित जाति का सदस्य",
  "Member of a Scheduled Tribe": "अनुसूचित जनजाति का सदस्य",
  "Victim of trafficking or beggar": "तस्करी या भिखारी का शिकार",
  "Victim of abuse of power": "सत्ता के दुरुपयोग का शिकार",
  "Woman or child": "महिला या बच्चा",
  "Person with disability": "दिव्यांग व्यक्ति",
  "Victim of disaster or mass violence": "आपदा या सामूहिक हिंसा का शिकार",
  "Industrial workman": "औद्योगिक श्रमिक",
  "In custody or jail": "हिरासत या जेल में",
  "Annual income below the prescribed limit": "वार्षिक आय निर्धारित सीमा से कम",
};