export const HI_LAYOUT: Record<string, string> = {
  "Start legal help": "कानूनी सहायता शुरू करें",
  "How it works": "यह कैसे काम करता है",
  "Your rights": "आपके अधिकार",
  "For professionals": "व्यवसायियों के लिए",
  "Nayasetu — home": "न्यायसेतु — मुख्य पृष्ठ",
  Primary: "मुख्य नेविगेशन",
  "Sign out": "साइन आउट",
  "Sign in": "साइन इन",
  "I need legal help": "मुझे कानूनी सहायता चाहिए",
  "Switch language": "भाषा बदलें",
  citizen: "नागरिक",
  provider: "व्यवसायी",
  admin: "प्रशासक",
  institutional: "संस्थागत",
  Citizens: "नागरिक",
  Professionals: "व्यवसायी",
  Institutions: "संस्थाएँ",
  Trust: "विश्वास",
  "Check eligibility": "पात्रता जाँचें",
  "Legal aid referral": "विधिक सहायता रेफरल",
  "My portal": "मेरा पोर्टल",
  Grievance: "शिकायत",
  "Assisted mode": "सहायता मोड",
  "Join as professional": "व्यवसायी के रूप में जुड़ें",
  Onboarding: "पंजीकरण",
  Verification: "सत्यापन",
  "Provider dashboard": "व्यवसायी डैशबोर्ड",
  "Institutional surface": "संस्थागत इंटरफ़ेस",
  "Capability status": "क्षमता स्थिति",
  "Secure · Private · Confidential": "सुरक्षित · निजी · गोपनीय",
  "Privilege boundary": "विशेषाधिकार सीमा",
  "Verified professionals, fair allocation, transparent process and institutional accountability. Not a lawyer marketplace.":
    "सत्यापित व्यवसायी, निष्पक्ष आवंटन, पारदर्शी प्रक्रिया और संस्थागत जवाबदेही। यह वकीलों का मार्केटप्लेस नहीं है।",
  "Nayasetu is not affiliated with any court, bar council or government body. Professional misconduct is a State Bar Council matter under s.35, Advocates Act 1961.":
    "न्यायसेतु किसी भी न्यायालय, बार काउंसिल या सरकारी निकाय से संबद्ध नहीं है। पेशेवर कदाचार अधिवक्ता अधिनियम 1961 की धारा 35 के अंतर्गत राज्य बार काउंसिल का विषय है।",
  "Skip to content": "मुख्य सामग्री पर जाएँ",
  "Page not found": "पृष्ठ नहीं मिला",
  "The page you are looking for does not exist.": "जिस पृष्ठ को आप खोज रहे हैं वह मौजूद नहीं है।",
};